<?php
/**
 * Base configuration. Do not edit this file for machine-specific settings
 */

return [
    'driver' => 'sqlite',

    // Relative path, resolved against the project root.
    'sqlite' => [
        'path' => 'data/worldbuilder.sqlite',
    ],

    // Base URL path the site is served from, without a trailing slash.
    // 'auto' works it out from the request; set an explicit path only to override.
    'base_path' => 'auto',

    'site_name' => 'Worldbuilder',

    // Uploads
    'upload_max_bytes' => 8 * 1024 * 1024,

    // Show PHP errors on screen. Turn off if you ever expose this beyond localhost.
    'debug' => true,
];
